FROM ubuntu:20.04

LABEL maintainer="Miguel Correia <miguel.r.correia@inesctec.pt>"

ENV WORKSPACE_DIR=/opt

WORKDIR ${WORKSPACE_DIR}

# Set up environment variables
ENV PATH=/srv/miniconda3/bin:$PATH

# Install dependencies
RUN apt-get update && apt-get install -y wget git

# Install Miniconda
RUN wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /srv/miniconda3 && \
    rm ~/miniconda.sh && \
    echo ". /srv/miniconda3/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate opendrift" >> ~/.bashrc

# Configure and install opendrift
RUN git clone https://github.com/OpenDrift/opendrift.git

RUN conda config --add channels conda-forge
RUN conda config --add channels terradue
RUN conda env create -f opendrift/environment.yml

    
SHELL ["conda", "run", "-n", "opendrift", "/bin/bash", "-c"]
SHELL ["/bin/bash", "--login", "-c"]

RUN conda install -y python=3.11 pip click click2cwl 

RUN /srv/miniconda3/envs/opendrift/bin/pip install --no-deps -e opendrift

RUN conda install -n opendrift -y click click2cwl

COPY . .

RUN /srv/miniconda3/envs/opendrift/bin/python setup.py install

RUN echo '#!/bin/bash' >> /usr/local/bin/animation && \
    echo 'source activate opendrift' >> /usr/local/bin/animation && \
    echo 'animation "$@"' >> /usr/local/bin/animation && \
    chmod +x /usr/local/bin/animation

